config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root 'posts#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :manage, :all
        cannot :destroy, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do | exception |
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.friendly.find(params[:post_id])
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    redirect_to post_path(@post), notice: t('comment_created')
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy!
    redirect_to post_path(@post), notice: t('comment_deleted')
  end

  def edit
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update!(comment_params)
      redirect_to post_path(@post), notice: t('comment_updated')
    else
      render 'edit'
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def create
    @post = Post.new(post_params)
    if @post.save!
      redirect_to @post, notice: t('post_created')
    else
      render 'new'
    end
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update!(post_params)
      redirect_to @post, notice: t('post_updated')
    else
      render 'edit'
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy!
    redirect_to posts_path, notice: t('post_deleted')
  end

  
  private

    def post_params
      params.require(:post).permit(:title, :summary)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/comments/_comment.html.haml
%p
  %strong name:
  = comment.name
%p
  %strong Comment:
  = comment.body
-if user_signed_in?
  %p
    = link_to 'Edit', edit_post_comment_path(@post,comment) if can? :update, User
    = link_to 'Delete', [comment.post, comment],method: :delete if can? :destroy, User

app/views/comments/edit.html.haml
%h1 Edit Comment
= form_with(model: [ @post, @post.comments.find(params[:id]) ], local: true) do |form|
  %p
    = form.label :name
    %br/
    = form.text_field :name
  %p
    = form.label :comment
    %br/
    = form.text_area :body
  %p
    = form.submit
= link_to 'Back', post_path(@post)

app/views/comments/new.html.haml
%h1 New Comment
= form_with(model: [ @post, @post.comments.build ], local: true) do |form|
  %p
    = form.label :name
    %br/
    = form.text_field :name
  %p
    = form.label :comment
    %br/
    = form.text_area :body
  %p
    = form.submit
= link_to 'Back', post_path(@post)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MY-BLOG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav style="text-align:right;">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.<br/>
    <%= link_to "Edit profile", edit_user_registration_path %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
  </nav>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.haml
= form_with model: @post, local: true do |form|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited
        this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  %p
    = form.label :title
    %br/
    = form.text_field :title
  %p
    = form.label :summary
    %br/
    = form.text_area :summary
  %p
    = form.submit

app/views/posts/edit.html.haml
%h1 Edit Post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/index.html.haml
-if user_signed_in?
  =link_to 'New post', new_post_path if can? :create, User
%h1 Listing Posts
= will_paginate @posts
%table
  %tr
    %th Title
    %th Summary
    %th 
  -@posts.each do |post|
    %tr
      %td 
        = post.title
      %td
        = post.summary
      %td
        = link_to 'Show', post_path(post) if can? :read, User
      -if user_signed_in?
        %td
          =  link_to 'Edit ', edit_post_path(post) if can? :update, User
        %td
          = link_to 'Delete', post_path(post),method: :delete if can? :destroy, User

app/views/posts/new.html.haml
%h1 New Post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p
  %strong Title:
  = @post.title
%p
  %strong summary:
  = @post.summary
%h2 Comments
= render @post.comments
-if user_signed_in?
  %p
    = link_to 'New Comment', new_post_comment_path(@post.id) if can? :create, User
  = link_to 'Edit Post', edit_post_path(@post) if can? :update, User
= link_to 'Back', posts_path